### PR TITLE
add paypal

### PR DESCRIPTION
**Pull request by lorenzo-dev1**
Doesn't really get **all** of your data (couldn't find a way to do that), but it gets most of the transactions.

### CODE REVIEW

**Comment by lorenzo-dev1** [comment]
I actually found a link which should download all the personal data (https://www.paypal.com/myaccount/privacy/data/dar), however I am not sure it contains the transaction history (I have request access to my data but haven't got it yet). 

In case the transactions are not included, how should I do to include both links in the entry?

**Comment by daviddavo** [comment]
I would add two entries:
- Paypal Account (The link to download your account's information)
- Paypal Transactions (The link to download the transactions)

**Comment by lorenzo-dev1** [comment]
> I would add two entries:
> 
>     * Paypal Account (The link to download your account's information)
> 
>     * Paypal Transactions (The link to download the transactions)

Done!

**Comment by daviddavo** [comment]
LGTM

**Pull request merged**
